use rustls::pki_types::{CertificateDer, PrivateKeyDer, PrivatePkcs8KeyDer};
use rustls::ServerConfig;
use std::io::Write;
use std::path::Path;
use std::sync::Arc;
use tokio_rustls::TlsAcceptor;

#[derive(Debug, thiserror::Error)]
pub enum TlsError {
    #[error("TLS I/O error: {0}")]
    Io(#[from] std::io::Error),
    #[error("TLS configuration error: {0}")]
    Config(String),
    #[error("certificate generation failed: {0}")]
    Rcgen(#[from] rcgen::Error),
    #[error("rustls error: {0}")]
    Rustls(#[from] rustls::Error),
}

/// Load TLS cert and key from disk, or generate a self-signed cert if absent.
///
/// If both `cert_path` and `key_path` exist: read them as raw DER bytes and
/// return them in rustls format.
///
/// If either is missing: generate a new ECDSA self-signed certificate using
/// rcgen, write the cert DER to `cert_path` and the PKCS#8 key DER to
/// `key_path` (key file created with mode 0o600 before any secret bytes are
/// written).
///
/// Returns the certificate chain and private key ready for use with rustls.
pub fn load_or_generate_cert(
    cert_path: &Path,
    key_path: &Path,
) -> Result<(Vec<CertificateDer<'static>>, PrivateKeyDer<'static>), TlsError> {
    let cert_exists = cert_path.exists();
    let key_exists = key_path.exists();

    if cert_exists != key_exists {
        // One file is present and one is missing — regenerating would silently
        // overwrite the surviving file and invalidate any peer trust.
        // Require the operator to explicitly delete both and restart.
        let (present, missing) = if cert_exists {
            (cert_path, key_path)
        } else {
            (key_path, cert_path)
        };
        return Err(TlsError::Config(format!(
            "TLS setup error: {:?} exists but {:?} does not. \
             Delete both files and restart to generate a new keypair.",
            present, missing,
        )));
    }

    if cert_exists && key_exists {
        let cert_der = std::fs::read(cert_path)?;
        let key_der = std::fs::read(key_path)?;

        // Determine remaining validity from the sidecar file written at
        // generation time.
        //
        // The sidecar (`cert_path` with `.expiry` extension) stores the exact
        // Unix epoch seconds of the certificate's notAfter field as a decimal
        // string.  Reading it directly is immune to mtime changes caused by
        // backups, `touch`, or filesystem migration.  If the sidecar is absent
        // (externally-issued cert, or cert predating this sidecar feature),
        // treat the cert as expired to trigger a regeneration warning.
        let expiry_path = cert_path.with_extension("expiry");
        // Read the sidecar separately so we can distinguish "absent" from
        // "present but unreadable" in the warning messages below.
        let sidecar_text = std::fs::read_to_string(&expiry_path).ok();
        let remaining_days: Option<u64> = sidecar_text.as_ref().and_then(|s| {
            let not_after_secs = s.trim().parse::<u64>().ok()?;
            let now_secs = std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .ok()?
                .as_secs();
            Some(not_after_secs.saturating_sub(now_secs) / 86400)
        });

        let (remaining_days, expiry_source) = if let Some(d) = remaining_days {
            (d, "exact")
        } else if sidecar_text.is_none() {
            // Sidecar absent: expiry is unknown (externally-issued cert or cert
            // predating the sidecar feature).  Return 0 days to trigger a renewal
            // warning — safer than estimating from mtime, which is wrong for certs
            // not generated by kithd.
            tracing::warn!(
                cert = ?cert_path,
                "TLS: certificate expiry sidecar missing; treating as expired. \
                 Delete {:?} and {:?} to regenerate.",
                cert_path, key_path,
            );
            (0_u64, "unknown")
        } else {
            // Sidecar present but we could not compute remaining days.  This
            // happens if the file contains non-numeric content or (extremely
            // unlikely) if the system clock is before the Unix epoch.  Treat
            // conservatively as expired so the operator sees a clear warning.
            tracing::warn!(
                cert = ?cert_path,
                "TLS: certificate expiry sidecar unreadable or system clock error; \
                 treating as expired.  Delete {:?} and {:?} to regenerate.",
                cert_path, key_path,
            );
            (0_u64, "unknown")
        };

        if remaining_days == 0 {
            tracing::warn!(
                cert = ?cert_path,
                expiry_source,
                "TLS: certificate is expired or expires today; \
                 delete {:?} and {:?} to regenerate",
                cert_path, key_path,
            );
        } else if remaining_days <= 30 {
            tracing::warn!(
                cert = ?cert_path,
                remaining_days,
                expiry_source,
                "TLS: certificate expires in {remaining_days} days ({expiry_source}); \
                 delete {:?} and {:?} to regenerate before it expires",
                cert_path, key_path,
            );
        } else {
            tracing::info!(
                cert = ?cert_path,
                remaining_days,
                expiry_source,
                "TLS: loaded existing certificate ({remaining_days} days until expiry, {expiry_source})"
            );
        }

        let cert = CertificateDer::from(cert_der);
        let key = PrivateKeyDer::from(PrivatePkcs8KeyDer::from(key_der));
        Ok((vec![cert], key))
    } else {
        // The SAN "kith.local" is intentionally a placeholder.  All kithd
        // TLS connections are made through TailnetCertVerifier, which accepts
        // any certificate and does not validate the SAN field.  Tailscale
        // provides cryptographic peer identity at the network layer; the
        // certificate is used solely for transport confidentiality, not
        // authentication.  The SAN value is therefore irrelevant for security.
        let rcgen::CertifiedKey { cert, signing_key } =
            rcgen::generate_simple_self_signed(vec!["kith.local".to_string()])?;

        let cert_der: Vec<u8> = cert.der().to_vec();
        let key_der: Vec<u8> = signing_key.serialize_der();

        // Write key first (mode 0o600) before the cert.  If the key write
        // fails nothing is on disk and the next startup regenerates cleanly.
        // If the subsequent cert write fails, the partial-presence check on
        // the next startup detects key-without-cert and requires the operator
        // to delete both files — the same safe-stop as the reverse ordering,
        // but without leaving a private key stranded.
        #[cfg(unix)]
        {
            use std::os::unix::fs::OpenOptionsExt;
            let mut key_file = std::fs::OpenOptions::new()
                .write(true)
                .create(true)
                .truncate(true)
                .mode(0o600)
                .open(key_path)?;
            key_file.write_all(&key_der)?;
        }

        std::fs::write(cert_path, &cert_der)?;
        #[cfg(not(unix))]
        compile_error!(
            "kithd TLS key generation is only supported on Unix platforms. \
             The non-Unix code path cannot restrict key file permissions to 0o600. \
             kithd targets Linux/musl exclusively; if you are porting to a non-Unix \
             platform, implement owner-only file permissions before removing this error."
        );

        // Write the exact notAfter Unix epoch (now + 365 days) to a sidecar
        // file so the load path can read the accurate expiry without parsing X.509.
        // rcgen::generate_simple_self_signed always uses a 365-day validity window.
        // Sidecar write failures are non-fatal: kithd still starts; expiry
        // warnings will fall back to the mtime heuristic on the next load.
        let not_after_secs = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_secs() + 365 * 86400)
            .unwrap_or(0);
        let expiry_path = cert_path.with_extension("expiry");
        let _ = std::fs::write(&expiry_path, not_after_secs.to_string());

        tracing::info!(
            "TLS: generated new self-signed certificate at {:?}",
            cert_path
        );
        let cert = CertificateDer::from(cert_der);
        let key = PrivateKeyDer::from(PrivatePkcs8KeyDer::from(key_der));
        Ok((vec![cert], key))
    }
}

/// Read the raw DER bytes from a certificate file on disk.
///
/// Used by `spawn_test_listener` to return the cert bytes to callers so
/// that test clients can configure a custom trust root.
pub fn cert_der_bytes(cert_path: &Path) -> Result<Vec<u8>, TlsError> {
    std::fs::read(cert_path).map_err(TlsError::Io)
}

/// Create a `TlsAcceptor` for use with tokio TCP listeners.
///
/// Calls `load_or_generate_cert` to obtain the certificate and key, then
/// builds a `rustls::ServerConfig` with no client authentication required.
pub fn make_tls_acceptor(cert_path: &Path, key_path: &Path) -> Result<TlsAcceptor, TlsError> {
    let (certs, key) = load_or_generate_cert(cert_path, key_path)?;
    let config = ServerConfig::builder()
        .with_no_client_auth()
        .with_single_cert(certs, key)?;
    Ok(TlsAcceptor::from(Arc::new(config)))
}

#[cfg(test)]
mod tests {
    use super::*;

    fn install_crypto_provider() {
        let _ = rustls::crypto::aws_lc_rs::default_provider().install_default();
    }

    fn tmp_paths(label: &str) -> (std::path::PathBuf, std::path::PathBuf) {
        let dir = std::env::temp_dir();
        let pid = std::process::id();
        let cert = dir.join(format!("kith-test-cert-{label}-{pid}.der"));
        let key = dir.join(format!("kith-test-key-{label}-{pid}.der"));
        let _ = std::fs::remove_file(&cert);
        let _ = std::fs::remove_file(&key);
        let _ = std::fs::remove_file(cert.with_extension("expiry"));
        (cert, key)
    }

    fn cleanup(cert: &std::path::Path, key: &std::path::Path) {
        let _ = std::fs::remove_file(cert);
        let _ = std::fs::remove_file(key);
        let _ = std::fs::remove_file(cert.with_extension("expiry"));
    }

    // Oracle: load_or_generate_cert must produce a non-empty cert chain and
    // persist both files when neither exists.
    #[test]
    fn test_generate_cert_when_absent() {
        let (cert_path, key_path) = tmp_paths("gen");

        let result = load_or_generate_cert(&cert_path, &key_path);
        assert!(result.is_ok(), "expected Ok, got: {:?}", result.err());
        let (certs, _key) = result.unwrap();
        assert!(!certs.is_empty(), "cert chain must be non-empty");
        assert!(cert_path.exists(), "cert file must be written");
        assert!(key_path.exists(), "key file must be written");

        #[cfg(unix)]
        {
            use std::os::unix::fs::PermissionsExt;
            let meta = std::fs::metadata(&key_path).unwrap();
            assert_eq!(
                meta.permissions().mode() & 0o777,
                0o600,
                "key file must be owner-read-write only"
            );
        }

        cleanup(&cert_path, &key_path);
    }

    // Oracle: after generation the sidecar file must contain a valid Unix epoch
    // seconds value greater than `now` and at most 366 days from now.
    // This confirms the expiry information is written at generation time so the
    // load path can read the real notAfter without parsing X.509 DER.
    #[test]
    fn test_generate_writes_expiry_sidecar() {
        let (cert_path, key_path) = tmp_paths("expiry");

        load_or_generate_cert(&cert_path, &key_path).expect("generation must succeed");

        let expiry_path = cert_path.with_extension("expiry");
        assert!(expiry_path.exists(), "expiry sidecar must be written");

        let content = std::fs::read_to_string(&expiry_path).expect("sidecar must be readable");
        let not_after: u64 = content
            .trim()
            .parse()
            .expect("sidecar must be a decimal u64");

        let now = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap()
            .as_secs();
        assert!(
            not_after > now,
            "sidecar notAfter ({not_after}) must be in the future (now={now})"
        );
        // rcgen uses 365 days; allow up to 366 days for clock skew in tests.
        assert!(
            not_after <= now + 366 * 86400,
            "sidecar notAfter must be within 366 days; got {not_after} (now={now})"
        );

        cleanup(&cert_path, &key_path);
    }

    // Oracle: a second call with the same paths must return the same cert bytes
    // (files are loaded, not regenerated).
    #[test]
    fn test_load_existing_cert() {
        let (cert_path, key_path) = tmp_paths("load");

        load_or_generate_cert(&cert_path, &key_path).expect("first generation");
        let cert_bytes_first = std::fs::read(&cert_path).unwrap();

        load_or_generate_cert(&cert_path, &key_path).expect("second load");
        let cert_bytes_second = std::fs::read(&cert_path).unwrap();

        assert_eq!(
            cert_bytes_first, cert_bytes_second,
            "cert must not change on second call (load path)"
        );

        cleanup(&cert_path, &key_path);
    }

    // Oracle: if only one of the two files is present, load_or_generate_cert
    // must return an error rather than silently overwriting the surviving file.
    #[test]
    fn test_partial_presence_returns_error() {
        let (cert_path, key_path) = tmp_paths("partial");

        // Create only the cert file; leave the key absent.
        std::fs::write(&cert_path, b"fake cert bytes").unwrap();

        let result = load_or_generate_cert(&cert_path, &key_path);
        assert!(
            result.is_err(),
            "expected Err when only cert exists, got Ok"
        );
        // The cert file must NOT have been overwritten.
        assert_eq!(
            std::fs::read(&cert_path).unwrap(),
            b"fake cert bytes",
            "surviving cert file must not be overwritten"
        );

        cleanup(&cert_path, &key_path);
    }

    // Oracle: if only the key file is present (cert absent), load_or_generate_cert
    // must return an error — not silently overwrite the surviving file.
    #[test]
    fn test_partial_presence_key_only_returns_error() {
        let (cert_path, key_path) = tmp_paths("partial-key-only");

        // Create only the key file; leave the cert absent.
        std::fs::write(&key_path, b"fake key bytes").unwrap();

        let result = load_or_generate_cert(&cert_path, &key_path);
        assert!(result.is_err(), "expected Err when only key exists, got Ok");
        // The key file must NOT have been overwritten.
        assert_eq!(
            std::fs::read(&key_path).unwrap(),
            b"fake key bytes",
            "surviving key file must not be overwritten"
        );

        cleanup(&cert_path, &key_path);
    }

    // Oracle: make_tls_acceptor must succeed and produce a usable TlsAcceptor.
    #[test]
    fn test_make_tls_acceptor() {
        install_crypto_provider();
        let (cert_path, key_path) = tmp_paths("acceptor");

        let result = make_tls_acceptor(&cert_path, &key_path);
        assert!(
            result.is_ok(),
            "make_tls_acceptor failed: {:?}",
            result.err()
        );

        cleanup(&cert_path, &key_path);
    }
}
